# permissions for end users to edit opensearchclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchcluster-editor-role
rules:
- apiGroups:
  - opensearch.opni.io.my.domain
  resources:
  - opensearchclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opensearch.opni.io.my.domain
  resources:
  - opensearchclusters/status
  verbs:
  - get
