# permissions for end users to view opensearchclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opensearchcluster-viewer-role
rules:
- apiGroups:
  - opensearch.opni.io
  resources:
  - opensearchclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - opensearch.opni.io
  resources:
  - opensearchclusters/status
  verbs:
  - get
